// Reference trace frames at 5fps — used only by TraceLayer for build-time JSX
// alignment when TRACE_MODE is enabled (see constants.ts). Real files under
// src/assets/trace/ instead of inline base64.
// Source: FALAI.mp4. Frame index N -> ms = N * 200.

export const TRACE_FPS = 5;
export const TRACE_FRAME_INTERVAL_MS = 200;

export const TRACE_FRAMES: string[] = [
  "/assets/trace/frame-000.jpg",
  "/assets/trace/frame-001.jpg",
  "/assets/trace/frame-002.jpg",
  "/assets/trace/frame-003.jpg",
  "/assets/trace/frame-004.jpg",
  "/assets/trace/frame-005.jpg",
  "/assets/trace/frame-006.jpg",
  "/assets/trace/frame-007.jpg",
  "/assets/trace/frame-008.jpg",
  "/assets/trace/frame-009.jpg",
  "/assets/trace/frame-010.jpg",
  "/assets/trace/frame-011.jpg",
  "/assets/trace/frame-012.jpg",
  "/assets/trace/frame-013.jpg",
  "/assets/trace/frame-014.jpg",
  "/assets/trace/frame-015.jpg",
  "/assets/trace/frame-016.jpg",
  "/assets/trace/frame-017.jpg",
  "/assets/trace/frame-018.jpg",
  "/assets/trace/frame-019.jpg",
  "/assets/trace/frame-020.jpg",
  "/assets/trace/frame-021.jpg",
  "/assets/trace/frame-022.jpg",
  "/assets/trace/frame-023.jpg",
  "/assets/trace/frame-024.jpg",
  "/assets/trace/frame-025.jpg",
  "/assets/trace/frame-026.jpg",
  "/assets/trace/frame-027.jpg",
  "/assets/trace/frame-028.jpg",
  "/assets/trace/frame-029.jpg",
  "/assets/trace/frame-030.jpg",
  "/assets/trace/frame-031.jpg",
  "/assets/trace/frame-032.jpg",
  "/assets/trace/frame-033.jpg",
  "/assets/trace/frame-034.jpg",
  "/assets/trace/frame-035.jpg",
  "/assets/trace/frame-036.jpg",
  "/assets/trace/frame-037.jpg",
  "/assets/trace/frame-038.jpg",
  "/assets/trace/frame-039.jpg",
  "/assets/trace/frame-040.jpg",
  "/assets/trace/frame-041.jpg",
  "/assets/trace/frame-042.jpg",
  "/assets/trace/frame-043.jpg",
  "/assets/trace/frame-044.jpg",
  "/assets/trace/frame-045.jpg",
  "/assets/trace/frame-046.jpg",
  "/assets/trace/frame-047.jpg",
  "/assets/trace/frame-048.jpg",
  "/assets/trace/frame-049.jpg",
  "/assets/trace/frame-050.jpg",
  "/assets/trace/frame-051.jpg",
  "/assets/trace/frame-052.jpg",
  "/assets/trace/frame-053.jpg",
  "/assets/trace/frame-054.jpg",
  "/assets/trace/frame-055.jpg",
  "/assets/trace/frame-056.jpg",
  "/assets/trace/frame-057.jpg",
  "/assets/trace/frame-058.jpg",
  "/assets/trace/frame-059.jpg",
  "/assets/trace/frame-060.jpg",
  "/assets/trace/frame-061.jpg",
  "/assets/trace/frame-062.jpg",
  "/assets/trace/frame-063.jpg",
  "/assets/trace/frame-064.jpg",
  "/assets/trace/frame-065.jpg",
  "/assets/trace/frame-066.jpg",
  "/assets/trace/frame-067.jpg",
  "/assets/trace/frame-068.jpg",
  "/assets/trace/frame-069.jpg",
  "/assets/trace/frame-070.jpg",
  "/assets/trace/frame-071.jpg",
  "/assets/trace/frame-072.jpg",
  "/assets/trace/frame-073.jpg",
  "/assets/trace/frame-074.jpg",
];

export function getTraceFrameForMs(ms: number): string {
  const idx = Math.min(Math.max(0, Math.floor(ms / TRACE_FRAME_INTERVAL_MS)), TRACE_FRAMES.length - 1);
  return TRACE_FRAMES[idx];
}
