// Reference trace frames at 5fps — used only by TraceLayer for build-time JSX
// alignment when TRACE_MODE is enabled (see constants.ts). Real files under
// src/assets/trace/ instead of inline base64.
// Source: FALAI.mp4. Frame index N -> ms = N * 200.

export const TRACE_FPS = 5;
export const TRACE_FRAME_INTERVAL_MS = 200;

export const TRACE_FRAMES: string[] = [
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-000.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-001.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-002.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-003.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-004.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-005.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-006.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-007.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-008.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-009.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-010.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-011.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-012.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-013.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-014.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-015.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-016.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-017.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-018.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-019.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-020.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-021.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-022.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-023.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-024.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-025.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-026.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-027.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-028.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-029.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-030.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-031.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-032.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-033.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-034.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-035.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-036.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-037.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-038.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-039.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-040.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-041.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-042.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-043.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-044.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-045.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-046.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-047.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-048.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-049.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-050.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-051.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-052.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-053.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-054.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-055.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-056.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-057.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-058.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-059.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-060.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-061.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-062.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-063.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-064.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-065.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-066.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-067.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-068.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-069.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-070.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-071.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-072.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-073.jpg",
  "/fal-ai-demo/src/assets/trace/fal-ai-demo-frame-074.jpg",
];

export function getTraceFrameForMs(ms: number): string {
  const idx = Math.min(Math.max(0, Math.floor(ms / TRACE_FRAME_INTERVAL_MS)), TRACE_FRAMES.length - 1);
  return TRACE_FRAMES[idx];
}
