// AUTO-GENERATED — reference trace frames at 5fps
// Source: Cursor Cloud Agents.mp4
// Frame index N -> ms = N * 200
// Extracted from base64 to real files under src/assets/trace-frames/ (see REFACTOR-PATTERNS.md 2a).

export const TRACE_FPS = 5;
export const TRACE_FRAME_INTERVAL_MS = 200;

export const TRACE_FRAMES: string[] = [
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-000.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-001.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-002.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-003.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-004.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-005.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-006.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-007.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-008.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-009.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-010.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-011.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-012.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-013.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-014.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-015.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-016.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-017.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-018.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-019.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-020.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-021.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-022.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-023.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-024.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-025.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-026.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-027.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-028.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-029.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-030.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-031.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-032.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-033.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-034.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-035.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-036.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-037.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-038.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-039.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-040.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-041.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-042.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-043.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-044.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-045.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-046.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-047.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-048.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-049.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-050.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-051.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-052.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-053.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-054.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-055.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-056.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-057.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-058.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-059.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-060.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-061.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-062.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-063.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-064.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-065.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-066.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-067.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-068.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-069.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-070.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-071.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-072.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-073.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/cursor-cloud-agents-demo-frame-074.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-075.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-076.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-077.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-078.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-079.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-080.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-081.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-082.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-083.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-084.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-085.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-086.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-087.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-088.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-089.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-090.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-091.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-092.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-093.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-094.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-095.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-096.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-097.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-098.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-099.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-100.jpg",
  "/cursor-cloud-agents-demo/src/assets/trace-frames/frame-101.jpg",
];

export function getTraceFrameForMs(ms: number): string {
  const idx = Math.min(Math.max(0, Math.floor(ms / TRACE_FRAME_INTERVAL_MS)), TRACE_FRAMES.length - 1);
  return TRACE_FRAMES[idx];
}
