// AUTO-GENERATED — reference trace frames at 5fps
// Source: Cursor Cloud Agents.mp4
// Frame index N -> ms = N * 200
// Extracted from base64 to real files under src/assets/trace-frames/ (see REFACTOR-PATTERNS.md 2a).

export const TRACE_FPS = 5;
export const TRACE_FRAME_INTERVAL_MS = 200;

export const TRACE_FRAMES: string[] = [
  "/assets/trace-frames/frame-000.jpg",
  "/assets/trace-frames/frame-001.jpg",
  "/assets/trace-frames/frame-002.jpg",
  "/assets/trace-frames/frame-003.jpg",
  "/assets/trace-frames/frame-004.jpg",
  "/assets/trace-frames/frame-005.jpg",
  "/assets/trace-frames/frame-006.jpg",
  "/assets/trace-frames/frame-007.jpg",
  "/assets/trace-frames/frame-008.jpg",
  "/assets/trace-frames/frame-009.jpg",
  "/assets/trace-frames/frame-010.jpg",
  "/assets/trace-frames/frame-011.jpg",
  "/assets/trace-frames/frame-012.jpg",
  "/assets/trace-frames/frame-013.jpg",
  "/assets/trace-frames/frame-014.jpg",
  "/assets/trace-frames/frame-015.jpg",
  "/assets/trace-frames/frame-016.jpg",
  "/assets/trace-frames/frame-017.jpg",
  "/assets/trace-frames/frame-018.jpg",
  "/assets/trace-frames/frame-019.jpg",
  "/assets/trace-frames/frame-020.jpg",
  "/assets/trace-frames/frame-021.jpg",
  "/assets/trace-frames/frame-022.jpg",
  "/assets/trace-frames/frame-023.jpg",
  "/assets/trace-frames/frame-024.jpg",
  "/assets/trace-frames/frame-025.jpg",
  "/assets/trace-frames/frame-026.jpg",
  "/assets/trace-frames/frame-027.jpg",
  "/assets/trace-frames/frame-028.jpg",
  "/assets/trace-frames/frame-029.jpg",
  "/assets/trace-frames/frame-030.jpg",
  "/assets/trace-frames/frame-031.jpg",
  "/assets/trace-frames/frame-032.jpg",
  "/assets/trace-frames/frame-033.jpg",
  "/assets/trace-frames/frame-034.jpg",
  "/assets/trace-frames/frame-035.jpg",
  "/assets/trace-frames/frame-036.jpg",
  "/assets/trace-frames/frame-037.jpg",
  "/assets/trace-frames/frame-038.jpg",
  "/assets/trace-frames/frame-039.jpg",
  "/assets/trace-frames/frame-040.jpg",
  "/assets/trace-frames/frame-041.jpg",
  "/assets/trace-frames/frame-042.jpg",
  "/assets/trace-frames/frame-043.jpg",
  "/assets/trace-frames/frame-044.jpg",
  "/assets/trace-frames/frame-045.jpg",
  "/assets/trace-frames/frame-046.jpg",
  "/assets/trace-frames/frame-047.jpg",
  "/assets/trace-frames/frame-048.jpg",
  "/assets/trace-frames/frame-049.jpg",
  "/assets/trace-frames/frame-050.jpg",
  "/assets/trace-frames/frame-051.jpg",
  "/assets/trace-frames/frame-052.jpg",
  "/assets/trace-frames/frame-053.jpg",
  "/assets/trace-frames/frame-054.jpg",
  "/assets/trace-frames/frame-055.jpg",
  "/assets/trace-frames/frame-056.jpg",
  "/assets/trace-frames/frame-057.jpg",
  "/assets/trace-frames/frame-058.jpg",
  "/assets/trace-frames/frame-059.jpg",
  "/assets/trace-frames/frame-060.jpg",
  "/assets/trace-frames/frame-061.jpg",
  "/assets/trace-frames/frame-062.jpg",
  "/assets/trace-frames/frame-063.jpg",
  "/assets/trace-frames/frame-064.jpg",
  "/assets/trace-frames/frame-065.jpg",
  "/assets/trace-frames/frame-066.jpg",
  "/assets/trace-frames/frame-067.jpg",
  "/assets/trace-frames/frame-068.jpg",
  "/assets/trace-frames/frame-069.jpg",
  "/assets/trace-frames/frame-070.jpg",
  "/assets/trace-frames/frame-071.jpg",
  "/assets/trace-frames/frame-072.jpg",
  "/assets/trace-frames/frame-073.jpg",
  "/assets/trace-frames/frame-074.jpg",
  "/assets/trace-frames/frame-075.jpg",
  "/assets/trace-frames/frame-076.jpg",
  "/assets/trace-frames/frame-077.jpg",
  "/assets/trace-frames/frame-078.jpg",
  "/assets/trace-frames/frame-079.jpg",
  "/assets/trace-frames/frame-080.jpg",
  "/assets/trace-frames/frame-081.jpg",
  "/assets/trace-frames/frame-082.jpg",
  "/assets/trace-frames/frame-083.jpg",
  "/assets/trace-frames/frame-084.jpg",
  "/assets/trace-frames/frame-085.jpg",
  "/assets/trace-frames/frame-086.jpg",
  "/assets/trace-frames/frame-087.jpg",
  "/assets/trace-frames/frame-088.jpg",
  "/assets/trace-frames/frame-089.jpg",
  "/assets/trace-frames/frame-090.jpg",
  "/assets/trace-frames/frame-091.jpg",
  "/assets/trace-frames/frame-092.jpg",
  "/assets/trace-frames/frame-093.jpg",
  "/assets/trace-frames/frame-094.jpg",
  "/assets/trace-frames/frame-095.jpg",
  "/assets/trace-frames/frame-096.jpg",
  "/assets/trace-frames/frame-097.jpg",
  "/assets/trace-frames/frame-098.jpg",
  "/assets/trace-frames/frame-099.jpg",
  "/assets/trace-frames/frame-100.jpg",
  "/assets/trace-frames/frame-101.jpg",
];

export function getTraceFrameForMs(ms: number): string {
  const idx = Math.min(Math.max(0, Math.floor(ms / TRACE_FRAME_INTERVAL_MS)), TRACE_FRAMES.length - 1);
  return TRACE_FRAMES[idx];
}
