import type { ComponentType } from "react";

export interface ProjectDef {
  /** Matches the example's directory name, and the `project` render-data key. */
  id: string;
  title: string;
  description: string;
  duration: string;
  aspect: "landscape" | "portrait";
  loadVideo: () => Promise<ComponentType>;
  loadStylesUrl: () => Promise<string>;
  loadPosterUrl?: () => Promise<string>;
}

export const projects: ProjectDef[] = [
  {
    id: "figma-agent-demo",
    title: "Figma — Native Agent",
    description: "AI agent generating an onboarding flow",
    duration: "30.8s",
    aspect: "landscape",
    loadVideo: () => import("../figma-agent-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../figma-agent-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../figma-agent-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "figma-motion-demo",
    title: "Figma Motion",
    description: "Product-launch intro — bloom, editor, dial, Goal Reached",
    duration: "20s",
    aspect: "landscape",
    loadVideo: () => import("../figma-motion-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../figma-motion-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../figma-motion-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "vercel-deploy-demo",
    title: "Vercel — Deploy Flow",
    description: "From code push to live preview",
    duration: "22.5s",
    aspect: "landscape",
    loadVideo: () => import("../vercel-deploy-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../vercel-deploy-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../vercel-deploy-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "vercel-knowledge-base-demo",
    title: "Vercel Knowledge Base",
    description: "Vercel's knowledge base product demo",
    duration: "28.1s",
    aspect: "landscape",
    loadVideo: () => import("../vercel-knowledge-base-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../vercel-knowledge-base-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../vercel-knowledge-base-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "claude-cowork-demo",
    title: "Claude Cowork",
    description: "Agent view — headline, prompt, response, Progress plan",
    duration: "20s",
    aspect: "landscape",
    loadVideo: () => import("../claude-cowork-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../claude-cowork-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../claude-cowork-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "claude-security-demo",
    title: "Claude Security",
    description: "Public beta announcement",
    duration: "19s",
    aspect: "landscape",
    loadVideo: () => import("../claude-security-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../claude-security-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../claude-security-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "claude-code-demo",
    title: "Claude Code — Agent View",
    description: "Orchestrated parallel subagents",
    duration: "36s",
    aspect: "landscape",
    loadVideo: () => import("../claude-code-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../claude-code-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../claude-code-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "claude-office-demo",
    title: "Claude for Excel, PowerPoint & Word",
    description: "Claude inside Microsoft Office",
    duration: "30s",
    aspect: "landscape",
    loadVideo: () => import("../claude-office-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../claude-office-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../claude-office-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "claude-code-financial-demo",
    title: "Claude Code — Financial Services",
    description: "Agent templates for financial services",
    duration: "30s",
    aspect: "landscape",
    loadVideo: () => import("../claude-code-financial-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../claude-code-financial-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../claude-code-financial-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "claude-opus48-demo",
    title: "Claude Code — Agent View (Opus 4.8)",
    description: "Orchestrated parallel subagents",
    duration: "36s",
    aspect: "landscape",
    loadVideo: () => import("../claude-opus48-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../claude-opus48-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../claude-opus48-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "cursor-jira-demo",
    title: "Cursor + Jira",
    description: "Replying to a Jira comment inside the editor",
    duration: "28.5s",
    aspect: "landscape",
    loadVideo: () => import("../cursor-jira-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../cursor-jira-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../cursor-jira-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "cursor-sdk-demo",
    title: "Cursor SDK",
    description: "Product demo — light paper variant",
    duration: "25.3s",
    aspect: "landscape",
    loadVideo: () => import("../cursor-sdk-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../cursor-sdk-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../cursor-sdk-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "cursor-sidechat-demo",
    title: "Cursor — Side Chats",
    description: "Selection sweep into a side chat",
    duration: "17.2s",
    aspect: "landscape",
    loadVideo: () => import("../cursor-sidechat-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../cursor-sidechat-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../cursor-sidechat-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "cursor-cloud-agents-demo",
    title: "Cursor Cloud Agents",
    description: "Cursor Cloud Agents product demo",
    duration: "20.4s",
    aspect: "landscape",
    loadVideo: () => import("../cursor-cloud-agents-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../cursor-cloud-agents-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../cursor-cloud-agents-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "fal-ai-demo",
    title: "fal.ai Assets",
    description: "Introducing fal Assets",
    duration: "15.1s",
    aspect: "landscape",
    loadVideo: () => import("../fal-ai-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../fal-ai-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../fal-ai-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "clerk-cli-demo",
    title: "Clerk CLI Setup",
    description: "Clerk CLI setup product demo",
    duration: "17.1s",
    aspect: "landscape",
    loadVideo: () => import("../clerk-cli-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../clerk-cli-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../clerk-cli-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "chatgpt-voice-demo",
    title: "ChatGPT Voice",
    description: "Voice mode composer and waveform",
    duration: "26s",
    aspect: "landscape",
    loadVideo: () => import("../chatgpt-voice-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../chatgpt-voice-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../chatgpt-voice-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "codex-demo",
    title: "OpenAI Codex",
    description: "Bug fix workflow",
    duration: "22s",
    aspect: "landscape",
    loadVideo: () => import("../codex-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../codex-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../codex-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "elevenlabs-montage-demo",
    title: "ElevenLabs — Agents Montage",
    description: "Titles, metrics, charts, watercolor globe",
    duration: "22s",
    aspect: "landscape",
    loadVideo: () => import("../elevenlabs-montage-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../elevenlabs-montage-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../elevenlabs-montage-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "higgsfield-mcp-demo",
    title: "Higgsfield MCP",
    description: "Prompt card, generated video tiles, snack-bag attach",
    duration: "38.1s",
    aspect: "landscape",
    loadVideo: () => import("../higgsfield-mcp-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../higgsfield-mcp-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../higgsfield-mcp-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "higgsfield-figma-demo",
    title: "Higgsfield for Figma",
    description: "Multiplayer canvas — brief, generate, ship a watch campaign",
    duration: "27s",
    aspect: "landscape",
    loadVideo: () => import("../higgsfield-figma-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../higgsfield-figma-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../higgsfield-figma-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "linear-agents-demo",
    title: "Linear — Linear for Agents",
    description: "Linear for Agents product demo",
    duration: "32s",
    aspect: "landscape",
    loadVideo: () => import("../linear-agents-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../linear-agents-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../linear-agents-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "allbirds-tree-runner-demo",
    title: "Allbirds — Tree Runner NZ",
    description: "Vertical social ad demo",
    duration: "25s",
    aspect: "portrait",
    loadVideo: () => import("../allbirds-tree-runner-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../allbirds-tree-runner-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../allbirds-tree-runner-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "fashionnova-the-edit-demo",
    title: "Fashion Nova — The Edit",
    description: "Vertical social ad demo",
    duration: "25s",
    aspect: "portrait",
    loadVideo: () => import("../fashionnova-the-edit-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../fashionnova-the-edit-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../fashionnova-the-edit-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "gymshark-geo-seamless-demo",
    title: "Gymshark — Geo Seamless",
    description: "Vertical social ad demo",
    duration: "19s",
    aspect: "portrait",
    loadVideo: () => import("../gymshark-geo-seamless-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../gymshark-geo-seamless-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../gymshark-geo-seamless-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "olipop-demo",
    title: "OLIPOP",
    description: "A new kind of soda — vertical social ad demo",
    duration: "20s",
    aspect: "portrait",
    loadVideo: () => import("../olipop-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../olipop-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../olipop-demo/poster.jpg").then((m) => m.default),
  },
  {
    id: "rhode-demo",
    title: "rhode — summer '26",
    description: "Vertical social ad demo",
    duration: "20s",
    aspect: "portrait",
    loadVideo: () => import("../rhode-demo/src/Video").then((m) => m.Video),
    loadStylesUrl: () => import("../rhode-demo/src/styles.css?url").then((m) => m.default),
    loadPosterUrl: () => import("../rhode-demo/poster.jpg").then((m) => m.default),
  },
];

export const getProject = (id: string): ProjectDef | undefined =>
  projects.find((p) => p.id === id);
